### ISSUE TITLE
Internal server error 

### ISSUE THREAD

**Issue by NansD** [EBM2018/teamy#21]
![image](https://user-images.githubusercontent.com/18481465/53720054-0dc04e00-3e60-11e9-8657-d5c42bd09fff.png)
good luck :)

**Comment by Nathanmalnoury** [comment]
**sad**
known issue, unknow reason.
not sure if we're going to solve :laughing:

**Comment by Nathanmalnoury** [comment]
Why do you need to access that anyway ?  🤔

**Comment by Nathanmalnoury** [comment]
proudly closing this issue :smile:

**Comment by NansD** [comment]
Congrats
